spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_incident
    username: local_incident
    password: local_incident
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
